# Credits: P. Madden, B. Charlier
#
# https://github.com/getkeops/keops/issues/85
#
# To build the conda package :
#   cd keops   # root folder of keops git
#   conda build -c pytorch -c nvidia .conda/recipe
#
# To cretate an environment
#   conda create -y -n pykeops_env -c local -c pytorch -c nvidia pykeops


{% set data = load_setup_py_data(setup_file="../../setup.py", from_recipe_dir=True) %}

package:
  name: {{ data.get("name")|lower }}
  version: {{ data.get("version") }}

build:
  noarch: python
  number: 0

requirements:
  build:
    - python 3.7
  run:
    - python 3.7
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('nvcc') }}
    - pytorch 1.6.*
    - numpy

source:
  path: ../../

about:
  home: https://www.kernel-operations.io/
  license: MIT
  license_file: licence.txt
  summary: Kernel Operations on the GPU, with autodiff, without memory overflows
  doc_url: https://www.kernel-operations.io/
  dev_url: https://github.com/getkeops/keops
