name: population_graphs
channels:
  - pytorch
  - pip
  - conda-forge
  - defaults
  - pyg
dependencies:
  - python==3.10.8
  - pytorch::pytorch==2.0.0
  - conda-forge::cudatoolkit
  - conda-forge::numpy==1.24.2
  - conda-forge::pip==23.0.1
  - conda-forge::scikit-learn==1.2.2
  - conda-forge::scipy==1.10
  - conda-forge::tqdm==4.65.0
  - conda-forge::pandas==1.5.3
  - pip:
    - torch-householder==1.0.1
    - pytorch_lightning==1.3.8
    - wandb==0.15.9
    - networkx==3.0
    - torchmetrics==0.6.0
    - torch-cluster==1.6.1
    - click==8.1.7
    - appdirs==1.4.4
    - torchdiffeq==0.2.2
    - protobuff==3.20
